- hosts: web
  become: yes
  tasks:
        - name: Build an image and push it to a private repo
          community.docker.docker_image:
              build:
                  path: "/home/edureka/Desktop"
              name: docker.io/vinothchandrasekaran/xyz-technologies
              #tag: test
              push: true
              source: build
          register: out
        - debug:
              var: out
        - name: start a container
          community.docker.docker_container:
             name: xyz-application
             image: vinothchandrasekaran/xyz-technologies
             state: started
             ports:
                 - 1234:8080
             #restart: true
          register: out
        - debug:
              var: out
             #- name: Deploying to kubernetes
        - name: Deploy application and service together in kubernetes
          #command: "kubectl --kubeconfig=/home/ubuntu/kubernetes/admin.conf apply -f /home/ubuntu/edureka-devops-xyz-project/project_required_files/deployment.yml"
          command: >
            kubectl --kubeconfig=/home/ubuntu/kubernetes/admin.conf apply
            -f /home/ubuntu/edureka-devops-xyz-project/project_required_files/deployment.yml
            -f /home/ubuntu/edureka-devops-xyz-project/project_required_files/service.yml
          register: out
        - debug:
              var: out
