kind: Service
apiVersion: v1
metadata:
    name: xyz-tech-service
spec:
    type: NodePort
    selector:
        app: xyz-tech-app
    ports:
        - port: 80 #cluster port
          targetPort: 8080 #container image port
